### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by quentinus95** [cdot/CrosswordGame#5]
Hi @cdot!

Would it be possible to add a Dockerfile and publish a Docker image when you release a new version of this software?

Maybe we can pick and edit it from https://github.com/tgmgroup/CrosswordGame/blob/master/Dockerfile?

Thanks!

**Comment by cdot** [comment]
Been wanting to explore using Docker for node.js for a while, so followed up on this. Published to Github Packages.
